# Generated by Django 5.0.6 on 2024-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_quarto_foto_quarto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('idade', models.CharField(max_length=3)),
                ('end', models.CharField(max_length=100)),
                ('quarto', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORTO', 'Conforto'), ('LUXO', 'Luxo')], max_length=15)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORTO', 'Conforto'), ('LUXO', 'Luxo')], max_length=15),
        ),
    ]
