# Generated by Django 5.0.6 on 2024-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reserva_alter_quarto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
